server:
  port: 8081

spring:
  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:postgresql://localhost:5432/cryptobot?currentSchema=cryptobot-catalog
    username: root
    password: root
    driverClassName: org.postgresql.Driver